apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # eW91cnBhc3N3b3Jk = "yourpassword" (ตัวอย่าง)
  MYSQL_ROOT_PASSWORD: eW91cnBhc3N3b3Jk
  MYSQL_PASSWORD: eW91cnBhc3N3b3Jk