apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo-app
        image: jhipster/todo:latest  # ใช้ Docker image ที่เชื่อมต่อกับ PostgreSQL
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/todo_db"  # เชื่อมต่อกับ PostgreSQL
        - name: SPRING_DATASOURCE_USERNAME
          value: "todo_user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080