apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo  # ใช้ app: todo ตรงกับ label ของ Deployment
    spec:
      containers:
      - name: todo-app
        image: prologic/todo:latest # ใช้ Docker image ที่เชื่อมต่อกับ PostgreSQL
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgresql://todo_user:password@postgres-service:5432/todo_db"  # เชื่อมต่อกับ PostgreSQL
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: NodePort
  selector:
    app: todo  # ใช้ app: todo ตรงกับ label ของ Deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080